name: CI Pipeline

on:
  push:
    branches:
      - main  # Adjust branch name as needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'  # or 'temurin', depending on your preference

      - name: Build with Maven
        run: mvn clean install

      - name: Run Tests
        run: mvn test
